## Find more information

### Tables and further analysis

This publication contains the headline poverty, child poverty and household income statistics. [Associated tables](download.html) are available for download and contain:

- all estimates used in the charts
- additional estimates, for example, the equivalent before-housing-costs estimates where charts show after-housing-costs estimates only (where available)
- additional relative and severe poverty and child poverty estimates including numbers, rates and compositions of those in poverty disaggregated by a wide range of personal and household characteristics

Additional analysis themes are based on the needs of users. If you have any suggestions for future analysis please [contact us](#contact).

### Local poverty analysis

The main poverty data source, the Family Resources Survey, provides information at national level only. Alternative data sources are not directly comparable with the official poverty estimates presented in this report.

More information on [local poverty and income analysis from alternative data sources](https://www.gov.scot/collections/poverty-and-income-inequality-statistics/#localstatistics) is available.

### Persistent poverty

[New figures on persistent poverty](persistent.html) were published on `r params$pub_day`.

Persistent poverty identifies the number of individuals living in relative poverty for 3 or more of the last 4 years. It therefore identifies people who have been living in poverty for a significant period of time, the rationale being that this is more damaging than brief periods spent with a low income, with the impacts affecting an individual through their lifetime.

One of the four [statutory child poverty target measures](cpupdate.html) is persistent child poverty after housing costs.

These figures come from the Understanding Society survey which tracks individuals over time. The persistent poverty figures are not directly comparable to the figures in this publication as they use different income definitions and cover different time periods, but they provide useful additional information on poverty in Scotland.

### Previous reports

#### Poverty and Income Inequality in Scotland

- [2016-19 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2016-19/)
- [2015-18 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2015-18/)
- [2014-17 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2014-17/)
- [2015/16 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2015-16/)
- [2014/15 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2014-15/)
- [2013/14 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2013-14/)
- [2012/13 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2012-13/)
- [2011/12 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2011-12/)
- [2010/11 report](https://www.gov.scot/publications/poverty-income-inequality-scotland-2010-11/)

#### Persistent Poverty in Scotland

- [Latest report](persistent.html)
- [2010-2018 report](https://www.gov.scot/publications/persistent-poverty-scotland-2010-2018/)
- [2010-2017 report](https://www.gov.scot/publications/persistent-poverty-scotland-2010-2017/)
- [2010-2016 report](https://www.gov.scot/publications/persistent-poverty-scotland-2010-2016/)
- [2010-2015 report](https://www.gov.scot/publications/persistent-poverty-scotland-2010-2015/)

### Scottish Government websites

Further analysis based on the `r abbr("FRS", "Family Resources Survey")` and `r abbr("HBAI", "Households Below Average Income")` datasets is published by the Scottish Government throughout the year on the Scottish Government's poverty and child poverty statistics webpages. These and other Scottish Government  statistics are available here:

- [Poverty and income inequality analysis](https://www.gov.scot/collections/poverty-and-income-inequality-statistics/)
- [Confidence limits surrounding Scotland's key poverty estimates](https://www.gov.scot/publications/poverty-in-scotland-methodology/pages/measurement-uncertainty/)
- [Child poverty analysis](https://www.gov.scot/collections/child-poverty-statistics/)
- [Wealth analysis](https://www.gov.scot/collections/wealth-statistics/)
- [Scottish Index of Multiple Deprivation](https://www.gov.scot/simd)
- [Further information on all Scottish Government statistics](https://www.gov.scot/about/how-government-is-run/statistics-and-research/)
- [Scottish Government approach to tackling poverty](https://www.gov.scot/policies/poverty-and-social-justice/)



