# National Statistics

Official and National Statistics are produced to high professional standards set out in the Code of Practice for Official Statistics. Both undergo regular quality assurance reviews to ensure that they meet customer needs and are produced free from any political interference.

Statistics assessed, or subject to assessment, by the UK Statistics Authority carry the National Statistics label, a stamp of assurance that the statistics have been produced and explained to high standards and that they serve the public good.

The designation of these statistics as National Statistics was confirmed in May 2012 following a compliance check by the Office for Statistics Regulation.

### How to access background or source data

The data collected for this statistical bulletin cannot be made available by Scottish Government for further analysis, as the Scottish Government is not the data controller. However, the data controller (the UK Department for Work and Pensions) are making the data available through the [UK Data Service](www.ukdataservice.ac.uk/)

### Correspondence and enquiries {#contact}

For enquiries about this publication please contact the lead statistician.

Maike Waldmann<br>
Communities Analysis Division

#### Email

social-justice-analysis@gov.scot

#### Phone

0131 244 5851<br>

### Complaints and suggestions

If you are not satisfied with our service or have any comments or suggestions, or for general enquiries about Scottish Government statistics, please write to the Chief Statistician.

#### Address

Scottish Government<br>
2W St Andrews House<br>
Edinburgh, EH1 3DG

#### Phone

0131 244 0302

#### Email

statistics.enquiries@gov.scot

If you would like to be consulted about statistical collections or receive notification of publications, please register your interest at [ScotStat](www.gov.scot/scotstat).

Details of [forthcoming publications](www.gov.scot/publications/official-statistics-forthcoming-publications/) are regularly published.

### Crown Copyright

You may use or re-use this information (not including logos) free of charge in any format or medium, under the terms of the [Open Government Licence](www.nationalarchives.gov.uk/doc/open-government-licence/).
