# Find more information

### Further analysis

The headline poverty and income inequality statistics can be found in the latest Poverty and Income Inequality in Scotland publication. The link to this and further analysis published throughout the year are available at: www.gov.scot/collections/poverty-and-income-inequality-statistics/

Additional analysis themes are based on the needs of users. If you have any suggestions for future analysis please email social-justice-analysis@gov.scot.

### Other Scottish Government websites

For further information on all Scottish Government statistics: www.gov.scot/topics/statistics/

### Scottish Government approach to tackling poverty and income inequality 

www.gov.scot/policies/poverty-and-social-justice/

### Local Authority level analysis and other geographies in Scotland

The persistent poverty figures presented here are from a sample survey which limits the analysis possible at smaller geographical areas. Similarly, the main poverty statistics for Scotland published in Poverty and Income Inequality in Scotland are only available at Scotland level. A few analyses are published for areas below Scotland level (e.g. poverty in rural and urban areas); however, it is not possible to produce reliable estimates at Local Authority level from this source. 

Information on poverty at Local Authority level is available from alternative sources although none of these include persistent poverty. These can be found at: www.gov.scot/collections/poverty-and-income-inequality-statistics/#localstatistics

### UK Government websites

Income dynamics publication (contains figures comparable with those found in this publication): www.gov.uk/government/statistics/income-dynamics-experimental

Households Below Average Income, Department for Work and Pensions (methodology and UK estimates): www.gov.uk/government/collections/households-below-average-income-hbai--2