# Official Statistics

Official and National Statistics are produced to high professional standards set out in the Code of Practice for Official Statistics. Both undergo regular quality assurance reviews to ensure that they meet customer needs and are produced free from any political interference.

### Correspondence and enquiries

For enquiries about this publication please contact:

Maike Waldmann
Communities Analysis Division,

Telephone: 0131 244 5851 
e-mail: social-justice-analysis@gov.scot

For general enquiries about Scottish Government statistics please contact:

Office of the Chief Statistician, Telephone: 0131 244 0442,
e-mail: statistics.enquiries@gov.scot

### How to access background or source data

The data collected for this statistical bulletin cannot be made available by Scottish Government for further analysis as Scottish Government is not the data controller. 

### Complaints and suggestions

If you are not satisfied with our service or have any comments or suggestions, please write to the Chief Statistician, Area GR, St Andrews House, Edinburgh, EH1 3DG, Telephone: (0131) 244 0302, e-mail statistics.enquiries@gov.scot. 

If you would like to be consulted about statistical collections or receive notification of publications, please register your interest at www.gov.scot/scotstat.

Details of forthcoming publications can be found at www.gov.scot/statistics.