---
title: "Poverty and Income Inequality in Scotland `r params$data_period` - analytical report" 
lang: "en"
description: "Analysis relating to poverty, household income, and income inequality in Scotland, including child poverty statistics, pensioner poverty, poverty for equality groups, and household income and income inequality statistics."
output:
  bookdown::html_document2:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: no

params:
  pub_day: "31 March 2022"
  data_period: "2018-21"
  data_period_5: "2016-21"
  data_year: "2020/21"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```

```{r}

library(tidyverse)
library(scales)
library(kableExtra)
library(htmltools)
library(ggiraph)
library(xml2)

source("R/00_colours.R")
source("R/00_functions.R")

povertycharts <- readRDS("data/povertycharts.rds")
htmltables <- readRDS("data/povertyhtmltables.rds")
povertytables <- readRDS("data/tables.rds")

# Theme ------------------------------------------------------------------------

mytheme <- theme_grey() +
  theme(text = element_text(colour = SGgreys[1], size = 14),
        line = element_line(colour = SGgreys[1],
                            linetype = 1,
                            lineend = 2,
                            size = 0.5),

        plot.title = element_text(hjust = 0, colour = SGgreys[1], size = 12),
        plot.caption = element_text(hjust = 1),
        plot.title.position = "plot",

        legend.position = "top",
        legend.title = element_blank(),

        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),

        axis.line.x = element_line(),
        axis.ticks.length = unit(2, "pt"),
        axis.ticks.y = element_blank(),

        axis.title = element_blank(),
        axis.text.y = element_blank())

theme_set(mytheme)

chapters <- c("_poverty_chapters/_chapter0.Rmd", 
              "_poverty_chapters/_chapter1.Rmd", 
              "_poverty_chapters/_chapter2.Rmd",
              "_poverty_chapters/_chapter3.Rmd",
              "_poverty_chapters/_chapter4.Rmd",
              "_poverty_chapters/_chapter5.Rmd")
```

```{r load_chapters, child = chapters}
```
