---
title: "Persistent Poverty in Scotland `r params$pub_period`"

output:
  bookdown::html_document2:
    number_sections: false
    fig_width: 7
    fig_height: 3
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
      smooth_scroll: no
      
params:
  pub_day: "26 March 2020"
  pub_period: "2010-2018"
  data_period_long: "2014 and 2018"
  data_period: "2014-2018"
  prev_period: "2013-2017"
  data_year: "2017-2018"

---

<!-- Include skip target at the top of the document -->

<script>
  $(document).ready(function(){
    $head = $('#header');
    $head.prepend('<div class=\"skiptarget\"><a id=\"maincontent\">-</a></div>')
    });
</script>

```{r setup, include = FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
library(tidyverse)
library(scales)
library(kableExtra)
library(htmltools)
library(ggiraph)

source("R/00_colours.R")

persistentcharts <- readRDS("data/persistentcharts.rds")
persistenttables <- readRDS("data/persistenttables.rds")

interactive <- function(chart, height = 3) {
  chart <- girafe(ggobj = chart, width = 1, height_svg = height, width_svg = 7)
  girafe_options(x = chart, 
               opts_hover(css = "fill: #fdd522; stroke: gray; fill-opacity: 1; stroke-opacity: 1"))
}

devnote <- function(md) {
  div(class = "devnote-text",
      div(class = "devnote-text__text",
          create_html(md)))  
}

create_html <- function(md) {
  htmltools::HTML(
    markdown::markdownToHTML(
      text = md, fragment.only = TRUE
    )
  )
}

mytheme <- theme_grey() +
  theme(text = element_text(colour = SGgreys[1], size = 14),

        line = element_line(colour = SGgreys[1],
                            linetype = 1,
                            lineend = 2,
                            size = 0.5),

        plot.title = element_text(hjust = 0, colour = SGgreys[1]),
        plot.subtitle = element_text(hjust = 0, colour = SGgreys[1]),
        plot.caption = element_text(hjust = 1),

        legend.position = "top",
        legend.title = element_blank(),

        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),

        axis.line.x = element_line(),
        axis.ticks.length = unit(2, "pt"),
        axis.ticks.y = element_blank(),

        axis.title = element_blank(),
        axis.text.y = element_blank())

theme_set(mytheme)

```

```{r child = "_persistent_chapters/_pers01.Rmd"}
```

```{r child = "_persistent_chapters/_pers02.Rmd"}
```

```{r child = "_persistent_chapters/_pers03.Rmd"}
```

```{r child = "_persistent_chapters/_pers04.Rmd"}
```

```{r child = "_persistent_chapters/_pers05.Rmd"}
```

```{r child = "_persistent_chapters/_pers06.Rmd"}
```

```{r child = "_persistent_chapters/_pers07.Rmd"}
```

```{r child = "_persistent_chapters/_pers08.Rmd"}
```

