**A Scottish Government Official Statistics publication**

Published on `r params$pub_day`

<button onclick = "window.print();" class = "btn noprint" >
  Print or save as PDF
</button>
<button onclick="location.href='download.html'" class = "btn noprint">
  Download tables
</button>

`r message("This is the latest release.")`

This publication presents estimates of the proportion of people, children, working-age adults and pensioners living in persistent poverty in Scotland and in the other countries in the UK. The estimates are used to monitor progress in reducing poverty.

The latest persistent poverty estimates relate to the period between January 2016 and December 2020. The first `r abbr("UK", "United Kingdom")`-wide lockdown due to the coronavirus (COVID-19) pandemic began in March 2020. The pandemic had a small impact on data collection, see the [Data source section](#corona-impact) for more information.

## Key points

- Between `r params$data_period_long`, `r persistenttables$tableScotland$pp %>% tail(1L)` of people in Scotland were in persistent poverty after housing costs. Persistent poverty rates were similar for children (`r persistenttables$tableScotland$ch %>% tail(1L)`), working-age adults (`r persistenttables$tableScotland$wa %>% tail(1L)`) and pensioners (`r persistenttables$tableScotland$pn %>% tail(1L)`). 

- Persistent child poverty saw a relatively large drop compared to previous estimates, and not all of this decrease is likely to be real. Persistent poverty estimates do tend to fluctuate. They also get revised when households re-enter the longitudinal sample and data gaps can be filled. However, some of the decrease is plausible in part due to increased financial support during the pandemic for some lower-income households. At the same time, reduced earnings and job losses may have resulted in a lower median income. This may have led to a fall in the poverty line, and thereby a drop in the relative poverty rate.

- Not everyone in poverty is in persistent poverty: More than a third of people in poverty move out of poverty each year. At the same time, a similar number of people who were not in poverty previously newly enter poverty each year.

## What you need to know

Poverty can be measured in a number of different ways, each of which can tell us something different about poverty. One of the most common measures is relative (income) poverty which identifies people living in households with an equivalised income below 60% of the UK median household income. It therefore measures whether those in the lowest income households are keeping pace with the growth of incomes in the economy as a whole. Statistics on relative poverty in Scotland can be found in the [Poverty and Income Inequality in Scotland](../2021) report.

The statistics in this report provide information on persistent poverty in Scotland. **Persistent poverty identifies individuals who live in relative poverty for three or more of the last four years.** It therefore identifies people who have been living in poverty for a significant period of time, which is more damaging than brief periods spent with a low income. The impacts can affect an individual throughout their lifetime.

The estimates in this publication are derived from the Understanding Society survey. Understanding Society is a `r abbr("UK", "United Kingdom")`-wide longitudinal survey that captures information about people’s social and economic circumstances, attitudes, behaviours and health. Being longitudinal, the same individuals are interviewed each year allowing identification of those who have been in poverty over a number of years.

Some estimates from previous years have been improved and will therefore differ between publications. The latest publication provides the most accurate estimates.

This publication presents persistent poverty estimates for seven overlapping periods from 2010-2014 to `r params$data_period`. It now also includes poverty entry and exit rates.

`r infobox("The statistics presented below are subject to a degree of uncertainty. This means that implied changes over the years and between countries may not be statistically significant and instead be within a given error range. More information can be found in the [Data source](#uncertainty) section.")`
