**An Official Statistics publication**

Published on `r params$pub_day`

`r devnote("This webpage is a development version for the next report. The data is from the last published report.")`

This publication presents estimates of the proportion of people, children, working-age adults and pensioners living in persistent poverty in Scotland and in the other countries in the UK. The estimates are used to monitor progress in reducing poverty.

## Key points

The statistics in this report provide information on persistent poverty in Scotland. They are taken from the Understanding Society survey and so, as is true for all statistics derived from survey data, the statistics are subject to a degree of error. This means that implied changes over the years and between UK countries may not be significant and instead be within a given error range. More information can be found in the [Methodology][Methodology] section.

Some estimates from previous years have been improved and will therefore differ between publications. The latest publication provides the most accurate estimates.

### All individuals

Between `r params$data_period_long`, `r persistenttables[["table1"]]$AHCpp %>% tail(1L)` of people in Scotland were in persistent poverty after housing costs. This compares to `r persistenttables[["table1"]]$AHCpp %>% tail(2L) %>% head(1L)` in `r params$prev_period`. 

### Children

Between `r params$data_period_long`, `r persistenttables[["table1"]]$AHCch %>% tail(1L)` of children in Scotland were in persistent poverty after housing costs. This compares to `r persistenttables[["table1"]]$AHCch %>% tail(2L) %>% head(1L)` in `r params$prev_period`.

Children have consistently had a higher risk of living in persistent poverty after housing costs than working-age adults and pensioners in Scotland.

### Working-age adults

Between `r params$data_period_long`, `r persistenttables[["table1"]]$AHCwa %>% tail(1L)` of working-age adults in Scotland were in persistent poverty after housing costs. This compares to `r persistenttables[["table1"]]$AHCwa %>% tail(2L) %>% head(1L)` in `r params$prev_period`.

### Pensioners

Between `r params$data_period_long`, `r persistenttables[["table1"]]$AHCpn %>% tail(1L)` of pensioners in Scotland were in persistent poverty after housing costs. This compares to `r persistenttables[["table1"]]$AHCpn %>% tail(2L) %>% head(1L)` in `r params$prev_period`.

### Scotland compared to other UK countries

`r devnote("manually update this section")`

When looking at the overall population, Scotland had similar levels of persistent poverty after housing costs to England and Wales (all 13%), and slightly higher rates than Northern Ireland (11%). 

The persistent child poverty rate after housing costs in Scotland and Northern Ireland (both 17%) was lower than in England (20%) and Wales (19%). This has been consistent over time. 

Persistent pensioner poverty after housing costs in Scotland (12%) was slightly higher compared to England and Wales (both 11%) and considerably higher compared to Northern Ireland (5%)
