## Definitions

### Measures of income 

The income used to determine persistent poverty in this publication includes:

* Labour income – usual pay and self-employment earnings. Includes income from second jobs.
* Miscellaneous income – educational grants, payments from family members and any other regular payment
* Private benefit income – includes trade union/friendly society payments, maintenance or alimony and sickness or accident insurance
* Investment income – private pensions/annuities, rents received, income from savings and investments
* Pension income – occupational pensions income
* State support – tax credits and all state benefits including State Pension

Income is net of the following items:

* income tax payments;
* National Insurance contributions;
* domestic rates / council tax;

Income is adjusted for household size and composition by means of equivalence scales, which reflect the extent to which households of different size and composition require a different level of income to achieve the same standard of living. This adjusted income is referred to as equivalised income (see definition below for more information on equivalisation). 

Income after housing costs (AHC) is derived by deducting a measure of housing costs derived from mortgage and rents from the above income measure. 

### Equivalisation 

Equivalisation is the process by which household income is adjusted to make it comparable across households of different size and composition. This reflects the fact that a bigger household requires more money than a smaller one to achieve the same standard of living. Further information on equivalisation can be found on the [Scottish Government poverty methodology webpages](https://www.gov.scot/publications/poverty-in-scotland-methodology/pages/income-equivalisation/)
