## Find more information

### Further analysis

The headline poverty and income inequality statistics can be found in the latest [Poverty and Income Inequality in Scotland report](./). Further analysis published throughout the year are available on the [Scottish Government poverty analysis website](www.gov.scot/collections/poverty-and-income-inequality-statistics/)

Additional analysis themes are based on the needs of users. If you have any suggestions for future analysis please [contact us](#contact).

### Previous reports

#### Persistent Poverty in Scotland

- [2010-2018 report](https://www.gov.scot/about/how-government-is-run/statistics-and-research/www.gov.scot/publications/persistent-poverty-scotland-2010-2018/)
- [2010-2017 report](https://www.gov.scot/about/how-government-is-run/statistics-and-research/www.gov.scot/publications/persistent-poverty-scotland-2010-2017/)
- [2010-2016 report](https://www.gov.scot/about/how-government-is-run/statistics-and-research/www.gov.scot/publications/persistent-poverty-scotland-2010-2016/)
- [2010-2015 report](https://www.gov.scot/about/how-government-is-run/statistics-and-research/www.gov.scot/publications/persistent-poverty-scotland-2010-2015/)

#### Poverty and Income Inequality in Scotland

- [Latest report](./)
- [2016-19 report](www.gov.scot/publications/poverty-income-inequality-scotland-2016-19/)
- [2015-18 report](www.gov.scot/publications/poverty-income-inequality-scotland-2015-18/)
- [2014-17 report](www.gov.scot/publications/poverty-income-inequality-scotland-2014-17/)
- [2015/16 report](www.gov.scot/publications/poverty-income-inequality-scotland-2015-16/)
- [2014/15 report](www.gov.scot/publications/poverty-income-inequality-scotland-2014-15/)
- [2013/14 report](www.gov.scot/publications/poverty-income-inequality-scotland-2013-14/)
- [2012/13 report](www.gov.scot/publications/poverty-income-inequality-scotland-2012-13/)
- [2011/12 report](www.gov.scot/publications/poverty-income-inequality-scotland-2011-12/)
- [2010/11 report](www.gov.scot/publications/poverty-income-inequality-scotland-2010-11/)

### UK Government websites

- [Income dynamics publication](www.gov.uk/government/statistics/income-dynamics-experimental) (contains figures comparable with those found in this publication)
- [Households Below Average Income](www.gov.uk/government/collections/households-below-average-income-hbai--2), Department for Work and Pensions (methodology and UK estimates)
